# Application running port
server:
    port: 8888

# Spring configuration with local git repository
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jgsudhakar735/SpringConfigServer.git # GIT URL
          username: # GIT User name
          password: # Password
          default-label: main # Branch name
          clone-on-start: true # to check whether the server reachable and clone
        jdbc:
          order: 1
          sql: SELECT app_configuration.param_name, app_configuration.param_value from app_configuration where APPLICATION = ? AND PROFILE= ? AND LABEL =?
      profile: git
  application:
    name: jgsudhakar-services # Application name , generally this will be the file name of the properties.
  devtools:
    add-properties: false
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring?createDatabaseIfNotExist=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    continue-on-error: true
  profiles:
    active: git # switch to jdbc to work with JDBC server configuration
  main:
    allow-bean-definition-overriding: true
